version: '3'

services:
  main:
    build:
      context: ./main
      dockerfile: Dockerfile 
    links:
      - db
    ports:
      - "80:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=engajamente
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql

